spring.application.name=$MICRO_NAME_USUARIO
spring.datasource.url=$DATABASE_USUARIO
spring.datasource.username=$USERNAME_USUARIO
spring.datasource.password=$PASSWORD_USUARIO
server.port=$PORT_USUARIO
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect