spring.application.name=$MICRO_NAME_EVALUACION
spring.datasource.url=$DATABASE_URL_EVALUACION
spring.datasource.username=$DATABASE_USERNAME_EVALUACION
spring.datasource.password=$DATABASE_PASSWORD_EVALUACION
server.port=$DATABASE_PORT_EVALUACION

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
Spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.validation=TRACE